### ISSUE TITLE
Start Google Cloud Storage gcssync for experts

### ISSUE THREAD

**Issue by qjhart** [ucd-library/aggie-experts#153]
One plan is to use google cloud storage as our methodology for storing startup data for our users, works, etc for our experts.  In order for this to work, we need to verify that gcsync works okay for our setup.

**Comment by qjhart** [comment]
I&rsquo;m following the instructions at [Pub/Sub for Cloud Storage](https://cloud.google.com/storage/docs/reporting-changes).  This is
combined with [FIN gcsync service](https://github.com/ucd-library/fin/blob/sandbox/docs/services/gcssync-service.md).


<a id="orgbd29a2b"></a>

# Before you begin

Starting at 4., topic name MUST match the bucket name.

PubSub,
  select [x] Add default Subscription
  [ ] Use a schema ?
  [ ] Enable Message Retention?

Then, I added a `mini` subscription, which matches the GCS<sub>BUCKET</sub><sub>NAME</sub>,
for the `aggie-experts-fcrepo-mini` topic/bucket

Go off book at item 5., not using the suggested service agent of the GCS
bucket manager.

I&rsquo;m making aggie-expert-data-harvester the pub/sub admin for the project.
This makes most sense, as they are the ones writing to the GCS, or they will
eventually.  I gave this the role of PUB/SUB publisher.

Questions,

-   Why not use the default subscription `aggie-experts-fcrepo-mini-sub`?
-   Where are the dams subscriptions?


<a id="org8f2c6d1"></a>

# Notification Configuration

Setup notifications for new additions to our mini setup.

    gcloud storage buckets notifications create gs://aggie-experts-fcrepo-mini --topic=aggie-experts-fcrepo-mini


<a id="orgf26ac2e"></a>

# FIN

Now, we&rsquo;ll see if we can setup the gcssync w/ the passed configuration.
This first example tries to put everything at root.

    {
        "sync" : {
    	"containers" : [
    	    {
    	    "bucket" : "aggie-experts-fcrepo-{{GCS_BUCKET_ENV}}",
    	    "basePath" : "/",
    	    "direction" : "gcs-to-fcrepo",
    	    "initDataHydration" : true
    	}
    	]
        }
    }

This seems to work just fine.  I do get a number of errors during the
update, specfically from aggie-experts-gateway, but they don&rsquo;t seem to cause
any issue.

    {
        "name":"fin-server-generic-localhost",
        "hostname":"6cca38593553",
        "pid":19,
        "level":50,
        "err":{
    	"message":"Cannot read properties of undefined (reading 'head')",
    	"name":"TypeError",
    	"stack":"TypeError: Cannot read properties of undefined (reading 'head')\n    at OcflObjectFile.#resolveContentPath (/fin/services/node_modules/@ocfl/ocfl/lib/object.js:69:70)\n    at async OcflObjectFile.asBuffer (/fin/services/node_modules/@ocfl/ocfl/lib/object.js:92:38)\n    at async DirectAccess.readOcfl (/fin/services/node-utils/lib/direct-access.js:290:21)\n    at async FinSearch.update (/fin/services/node-utils/lib/fin-cache.js:145:17)\n    at async FinSearch.onFcrepoEvent (/fin/services/node-utils/lib/fin-cache.js:49:9)\n    at async ServiceModel._onFcrepoEvent (/fin/services/gateway/models/services.js:390:7)\n    at async Subscription._onMessageCallback (/fin/services/node-utils/lib/activemq/stomp.js:185:11)"
        },
        "msg":"Cannot read properties of undefined (reading 'head')",
        "time":"2023-08-08T23:37:02.447Z",
        "v":0}
